name: tp_airbnb
recipe: lamp
config:
  php: '7.4'
  webroot: .
  xdebug: 'develop,debug'
services:
  appserver:
    config:
      php: ./.lando.config/php.ini/php.ini
  database:
    portforward: 3307